# Generated by Django 5.2.5 on 2025-08-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
    ]
