version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:61000
    volumes:
      - .:/app
    ports:
      - "61000:61000"
    environment:
      - DEBUG=1
      - SECRET_KEY=supersecretkey
